version: "2"


services:
    timeseries-db:
        extends:
            file: timeseries_sds/app.yml
            service: db
        networks:
            internal:
                aliases:
                    - timeseries-db.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-timeseries-db
    fault-dc:
        extends:
            file: fault_dc/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - fault-dc.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-fault-dc
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
    timeseries-db-input:
        extends:
            file: timeseries_sds/app.yml
            service: telegraf
        networks:
            internal:
                aliases:
                    - timeseries-input.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-timeseries-input
        restart: unless-stopped
        depends_on:
            - "timeseries-db"
            - "mqtt_broker"
    timeseries-db-input-fault:
        extends:
            file: timeseries_sds/app.yml
            service: telegraf_fault
        networks:
            internal:
                aliases:
                    - timeseries-input-fault.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-timeseries-input-fault
        restart: unless-stopped
        depends_on:
            - "timeseries-db"
            - "mqtt_broker"
    timeseries-db-input-track:
        extends:
            file: timeseries_sds/app.yml
            service: telegraf_tracking
        networks:
            internal:
                aliases:
                    - timeseries-input-track.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-timeseries-input-track
        restart: unless-stopped
        depends_on:
            - "timeseries-db"
            - "mqtt_broker"
    timeseries-db-input-worker:
        extends:
            file: timeseries_sds/app.yml
            service: telegraf_worker
        networks:
            internal:
                aliases:
                    - timeseries-input-worker.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-timeseries-input-worker
        restart: unless-stopped
        depends_on:
            - "timeseries-db"
            - "mqtt_broker"
    dashboard:
        extends:
            file: dashboard_ui/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - dashboard-ui.docker.local
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
            - "timeseries-db"
    utilisation:
        extends:
            file: utilisationCalc/app.yml
            service: appUtil
        networks:
            internal:
                aliases:
                    - utilisation.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-utilisation
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
            - "timeseries-db"
    worker-tracking-app:
        extends:
            file: worker_tracking/app.yml
            service: worker_tracking
        networks:
            internal:
                aliases:
                    - worker.tracking.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-worker-tracking
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
            - "timeseries-db"
    mqtt_broker:
        extends:
            file: mqtt_broker/app.yml
            service: app
        restart: unless-stopped
        logging:
            driver: syslog
            options:
                tag: docker-mqtt-broker
        networks:
            internal:
                aliases:
                    - mqtt.docker.local

networks:
    internal:
        name: manualLab
        external: true
