version: "2"

services:
    workerTracking:
        build: .
        privileged: true
        volumes:
            - ./config:/app/config
            -./data:/app/data
        environment:
            - DOCKER_INFLUXDB_ORG=${DB_ORG}
            - DOCKER_INFLUXDB_BUCKET=${DB_BUCKET}
            - DOCKER_CURRENT_INFLUXDB_TOKEN=${DB_ADMIN_INITIAL_TOKEN}
